# Generated by Django 5.2.8 on 2025-11-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TimeField(max_length=50)),
            ],
        ),
    ]
